version: '3.8'

services:
  # Main application (with feature flags)
  app:
    build: .
    container_name: cet-app
    ports:
      - "9095:9095"
    environment:
      - FLASK_PORT=9095
      - FEATURE_FLAGS={"useV2DashboardApi":false,"useV2Charts":false,"useV2Tables":false}
      - V2_ROLLOUT_PERCENTAGE=10
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./app.py:/app/app.py
      - ./repositories:/app/repositories
      - ./services:/app/services
    networks:
      - cet-network

  # V1-only instance for comparison testing
  app-v1:
    build: .
    container_name: cet-app-v1
    ports:
      - "9096:9095"
    environment:
      - FLASK_PORT=9095
      - FEATURE_FLAGS={"useV2DashboardApi":false}
      - V2_ROLLOUT_PERCENTAGE=0
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./app.py:/app/app.py
      - ./repositories:/app/repositories
      - ./services:/app/services
    networks:
      - cet-network

  # V2-only instance for testing
  app-v2:
    build: .
    container_name: cet-app-v2
    ports:
      - "9097:9095"
    environment:
      - FLASK_PORT=9095
      - FEATURE_FLAGS={"useV2DashboardApi":true, "useV2Charts":true, "useV2Tables":true}
      - V2_ROLLOUT_PERCENTAGE=100
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./app.py:/app/app.py
      - ./repositories:/app/repositories
      - ./services:/app/services
    networks:
      - cet-network

  # Nginx for load balancing and A/B testing
  nginx:
    image: nginx:alpine
    container_name: cet-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - app-v1
      - app-v2
    networks:
      - cet-network

networks:
  cet-network:
    driver: bridge